spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vigilapp
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db.changelog.xml
    default-schema: public

server:
  error:
    include-message: always

info:
  app:
    name: Fram Vigilapp
    description: API para la vigilancia
    version: 1.0.0
